### ISSUE TITLE
recipe for glowing frame

### ISSUE THREAD

**Issue by Cyclopropinon** [RealityTest/ciif#6]
is it possible to make it toggleable whether u want to use glowdust or glow inc(similar to the vanilla recipe)?

**Comment by RealityTest** [comment]
This was my original plan. Unfortunately it's not easily possible since the library I'm using to create the recipe can't overwrite vanilla recipes. Vanilla crafting ignores NBT data on items so it would just return a regular glow item frame. This would require a lot of rewriting the vanilla crafting code which is not really within the scope of this mod.

**Comment by Cyclopropinon** [comment]
ok interesting to know
tyvm for your answer
